--
-- SET PRIVILEGES ON SCHEMA taxi_service
--
CREATE USER 'taxi_service'@'%' IDENTIFIED BY 'jXmXIUZ@t66.cq7U';
GRANT USAGE ON *.* TO 'taxi_service'@'%';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `taxi\_service`.* TO 'taxiservice'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
